# Generated by Django 5.2.5 on 2025-09-02 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('score',
                 models.PositiveSmallIntegerField(
                     validators=[
                         django.core.validators.MinValueValidator(1),
                         django.core.validators.MaxValueValidator(5)],
                     verbose_name='Оценка')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('comment',
                 models.TextField(
                     blank=True,
                     verbose_name='Комментарий')),
            ],
        ),
    ]
