# Generated by Django 5.2.5 on 2025-09-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='given_evaluations',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='evaluations',
                to='tasks.task',
                verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='received_evaluations',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={
                (
                    'task',
                    'user',
                    'created_by')},
        ),
    ]
