# Generated by Django 5.2.5 on 2025-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=100)),
                ('description',
                 models.TextField(
                     blank=True)),
                ('start_time',
                 models.DateTimeField()),
                ('end_time',
                 models.DateTimeField()),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
