# Generated by Django 5.2.5 on 2025-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=255,
                     unique=True)),
                ('invite_code',
                 models.CharField(
                     blank=True,
                     editable=False,
                     max_length=12,
                     unique=True,
                     verbose_name='Код для приглашения')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
            ],
        ),
    ]
