version: '3.11'


services:
  db:
    image: postgres:14
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"


  web:
    build: .
    command: >
      sh -c "
              echo '⏳ Ждём базу...' &&
              python wait_for_db.py &&
              echo '✅ Генерируем миграции...' &&
              python manage.py makemigrations &&
              echo '✅ Применяем миграции...' &&
              python manage.py migrate &&
              echo '🚀 Запускаем сервер Django...' &&
              python manage.py runserver 0.0.0.0:8000
            "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
