# Generated by Django 5.2.5 on 2025-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=100,
                     verbose_name='Название')),
                ('description',
                 models.TextField(
                     verbose_name='Описание')),
                ('status',
                 models.CharField(
                     choices=[
                         ('to_do',
                          'Запланирована'),
                         ('in_progress',
                          'В процессе'),
                         ('done',
                          'Готова')],
                     default='to_do',
                     max_length=20,
                     verbose_name='Статус задачи')),
                ('deadline',
                 models.DateTimeField(
                     verbose_name='Срок исполнения')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('content',
                 models.TextField(
                     verbose_name='Комментарий')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='Создано')),
            ],
            options={
                'ordering': (
                    'created_at',
                ),
            },
        ),
    ]
